bin/rfid-controller usr/bin

src/icons/16x16/rfid-controller.png     usr/share/icons/hicolor/16x16/apps
src/icons/24x24/rfid-controller.png     usr/share/icons/hicolor/24x24/apps
src/icons/32x32/rfid-controller.png     usr/share/icons/hicolor/32x32/apps
src/icons/64x64/rfid-controller.png     usr/share/icons/hicolor/64x64/apps
src/icons/128x128/rfid-controller.png   usr/share/icons/hicolor/128x128/apps
src/icons/256x256/rfid-controller.png   usr/share/icons/hicolor/256x256/apps
src/icons/512x512/rfid-controller.png   usr/share/icons/hicolor/512x512/apps

debian/rfid-controller.desktop          usr/share/applications
